### PR TITLE
Added IRdq to DAIM; DAE Y-bus 'works'

### PR DESCRIPTION
**Pull request by natepallo**
Added IRdq to DAIMIB, or rather DAIMIB2 calls DAIM_IRdq for the ODEs and DAE terms. DAIM_IRdq specifically has a modified current_control_extref function that takes vg_d and vg_q inputs (y values) instead of the vg times sin or cos as in the D'Arco code.

I did possibly 'revert' some DAIM and DArcoEPSR122 code because I think was following an older plan of generalization, and I just wanted it to work as a standalone for comparison.

Still might not be working perfectly e.g. checking vg or vo might not be correct.. looking to explore more later.

### CODE REVIEW

**Comment by jd-lara** [comment]
@natepallo have you manage to make any progress on this?

**Comment by natepallo** [comment]
Just finished a backlog of grading, so working on it now. It looks like the
voltage regulator is supposed to be keeping the output (e_g in Markovic,
v_o in D'Arco) to 1.02 pu, but it doesn't look like a basis issue since it
is present in the original D'Arco simulation results. I'm checking the v
droop controller again, but also the initial conditions as we discussed.

-Nate

**Comment by ciaranrob** [comment]
This isn't a problem. We're not explicitly regulating voltage but rather regulating reactive power flow. Therefore we shouldn't expect the output to be kept at 1.02. We can chat about it more tomorrow if you would like. I think everything is (generally) working as expected.

**Comment by jd-lara** [comment]
The only way we could explicitly regulate voltage would be if we by-pass the reactive power droop control and feedback into the VCO the terminal voltage directly.

**Comment by natepallo** [comment]
I'm free anytime after 2 tomorrow, or alternatively now until 5 or so.

-Nate

**Comment by jd-lara** [comment]
We are in SDH now if you can join

**Comment by natepallo** [comment]
OK I'm on my way up.

**Pull request merged**
