### PR TITLE
Dc side

### PR DESCRIPTION
**Pull request by ciaranrob**
Initial commit of battery model

### CODE REVIEW

**Comment by natepallo** [comment]
Sorry, I am just getting to this today. I'm pretty sure I have the right branch and version (dc_side, acf0ef3).

Assuming battery_test is the fn to run? It looks like some of the function calls are outdated? To get the code to work, I had to do two things:
in battery_test.m: DAIIB_dc_side = @DAIIB_battery;
in DAIIB_battery: dc_side = @battery;

@ciaranrob, are these assumptions correct? Did I miss something?

**Comment by ciaranrob** [comment]
I thought I had a working script but yes I think I was using old function
calls. Thanks for catching that.

Is the code working for you now?

**Comment by natepallo** [comment]
Yes, if I make those two changes I get 5 plots when I run battery_test.m. How much do you want me to look into this? I don't 100% understand how the model comes together, and if you wanted me to check that, whichever reference you were using would help. For instance, in
`     %d(v_dc)/dt =
     i_dc/c_dc-(d1.^2*Ts*v_in)/(2*l_b*c_dc)-(vod*icvd+voq*icvq)/(v_dc*c_dc);`
I am not sure what the second term with Ts is for, though it would appear to be inductor current ripple. If that is the case, we might want to check what Ts is supposed to be, since it maps to the switching frequency in battery.m, not switching period.

**Comment by ciaranrob** [comment]
Don't spend too much time looking into it.

I'll present the model as is on Monday and then we can get together
afterwards and discuss it more.

**Comment by natepallo** [comment]
Got it. Sure - voltage dips momentarily at step in p_ref and dip in v_in (due to battery internal resistance?) seems reasonable enough to demonstrate as is. Recommend pushing updated function calls so that battery_test works out of the box before merging.

**Pull request merged**
