### PR TITLE
Fixed some eqn errors, possibly better inits

### PR DESCRIPTION
**Pull request by natepallo**
Combed through most of the eqns on page 158 of D'Arco et al EPSR 122 (2014). Found a missing w_g in the last equation, and a sign error in d_iod/dt (should be -cos and not +), at least in terms of consistency within the paper itself. Also may have better init terms from some calculations. Disabled damping and enabling voltage feed-forward is listed as a starting pointin III.A of D'Arco et al in IEEE PSCC (2014) and alluded to in the journal version EPES 72 (2015).

With these two steps, fsolve seems to generate a reasonable x from the x0 in params file.

Will continue checking the remaining equations (d_icv/dt and d_gamma/dt are the only two I haven't touched yet) on page 158 of EPSR tomorrow, 3/20.

### CODE REVIEW

**Comment by jd-lara** [comment]
Do you want to merge as is or want to wait until making better progress?

**Comment by natepallo** [comment]
I am fine with waiting until tomorrow. I think it is reasonable that there is still an error given that it works with k_AD = 0 but not otherwise; k_AD is in 2/4 equations I didn't get to.

**Comment by natepallo** [comment]
It turns out I was disabling kd, which is different from disabling kad - which was mentioned in the paper.  Will still see if there is anything wrong with the last four equations tomorrow.

**Comment by natepallo** [comment]
OK, I went back through again and found that the sign error seemed to be the only one. After I add and use init parameters mostly from the two D'Arco journal papers - as well as some inferred from d/dt =0 at steady state. Looks like it at least initializes correctly now.

**Comment by natepallo** [comment]
Give me a minute, I'm finalizing some additional fixes that really helped

**Comment by natepallo** [comment]
OK I'm pretty happy with this. I have a file DArcoEPSR122.m that you can run to generate plots 8-13 of the D'Arco paper.

Possibly significant for general code use, I added tvar_fun to the parameter structure. From the comment within the D'Arco script:

% Time varying parameters need to be executed inside of ode solver so a
% function can be embedded in the parameter structure passed to the solver.
% Specific time varying statements can be defined at the bottom of the
% script.

**Comment by natepallo** [comment]
tvar_fun might not be the most elegant, because I imagine it's constantly updating the full parameter structure this way, but it worked at least. It also required the statement at the top of inverter_infinite_bus:
    inverter_params = inverter_params.tvar_fun(t, inverter_params);
as well as a default function in parameters.m:
function inverter_params_out = default(t,inverter_params_in)
    inverter_params_out = inverter_params_in;
end
to maintain generality.

I'm sure we might be able to find a better way to do this in the future.

**Comment by jd-lara** [comment]
We can merge this and do the split later. At least @ciaranrob can branch out to implement DC dynamics.

**Pull request merged**
